name: The Marketing Advantage
favicon: null
layout_spectrum: 0.7116761468350887
typography_spectrum: 0.17947
title: Innovative Small Business Marketing Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#003e63'
    - '#6ec574'
    - '#00acde'
    - '#f5b963'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
